# Generated by Django 2.2.9 on 2020-01-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
