# Generated by Django 2.2.9 on 2020-01-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_auto_20200127_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='zipcode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
