# Generated by Django 2.2.9 on 2020-02-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0004_auto_20200201_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='is_ambassador',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='is_distributor',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='is_r_certified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='is_trainee',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='is_trichology',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
