# Generated by Django 2.2.9 on 2020-02-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0006_auto_20200204_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
