# Generated by Django 2.2.9 on 2020-02-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0007_consultant_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='web_site',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
