# Generated by Django 2.2.9 on 2020-02-22 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0008_auto_20200209_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='is_ambassador',
            new_name='ambassador',
        ),
        migrations.RenameField(
            model_name='consultant',
            old_name='is_approved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='consultant',
            old_name='is_distributor',
            new_name='distributor',
        ),
        migrations.RenameField(
            model_name='consultant',
            old_name='is_r_certified',
            new_name='r_certified',
        ),
        migrations.RenameField(
            model_name='consultant',
            old_name='is_trainee',
            new_name='trainee',
        ),
        migrations.RenameField(
            model_name='consultant',
            old_name='is_trichology',
            new_name='trichology',
        ),
    ]
