# Generated by Django 2.2.11 on 2020-03-08 00:48

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('body', markdownx.models.MarkdownxField()),
                ('background_image', models.ImageField(default='img/header.jpg', upload_to='backgrounds/2020/03/08')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
