# Generated by Django 2.2.11 on 2020-03-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='background_image',
            field=models.ImageField(default='img/header.jpg', upload_to='backgrounds/2020/03/09'),
        ),
    ]
