# Generated by Django 2.2.11 on 2020-03-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200309_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='background_image',
            field=models.ImageField(default='img/header.jpg', upload_to='backgrounds/2020/03/11'),
        ),
    ]
