# Generated by Django 2.2.11 on 2020-04-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200311_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='background_image',
            field=models.ImageField(default='img/header.jpg', upload_to='backgrounds/2020/04/04'),
        ),
    ]
